[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source ~/.vim/plugins/caw.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.vim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = 'source ~/.vim/plugins/airline-themes.vim'

[[plugins]]
repo = 'dracula/vim'
hook_add = 'autocmd MyAutoCmd VimEnter * nested colorscheme dracula'
