[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source ~/.vim/plugins/caw.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = 'source ~/.vim/plugins/solarized.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/.vim/plugins/auto-save.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'airblade/vim-gitgutter'
