[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source ~/.vim/plugins/caw.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.vim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = 'source ~/.vim/plugins/airline-themes.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.vim/plugins/fzf.vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
  autocmd VimEnter * nested colorscheme dracula
  autocmd ColorScheme * highlight Normal ctermbg=none
'''
